# https://github.com/PHPirates/travis-ci-latex-pdf

language: generic

before_install:
  # Install makeindex, if you do not use an index you can remove this (also remove the extra makeindex call).
  - sudo apt-get install texlive-binaries

install:
  # Silent install from conda docs
  # https://conda.io/docs/user-guide/install/macos.html#install-macos-silent
  # adapted using
  # https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html

  # Needed to check if conda already installed
  - export PATH="$HOME/miniconda/bin:$PATH"

  # If not yet installed, obtain Miniconda
  # and tectonic
  # From tectonic docs
  # https://tectonic-typesetting.github.io/en-US/install.html#the-anaconda-method
  - if ! command -v conda > /dev/null; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda -u;
      conda config --add channels conda-forge;
      conda config --set always_yes yes;
      conda install tectonic==0.1.10;
    fi
  - conda info -a
  # Workaround until tectonic 0.1.11 is available
  - sudo mkdir -p ~/.config/Tectonic/
  - echo "[[default_bundles]]" | sudo tee --append ~/.config/Tectonic/config.toml
  - sudo echo "url = \"https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.tar\"" | sudo tee --append ~/.config/Tectonic/config.toml
cache:
  directories:
    - $HOME/miniconda
    - $HOME/.cache/Tectonic
script:
  - tectonic ./main.tex --print
before_deploy:
  - mkdir pages
  - cp main.pdf pages/LocalConstitutionAndBylaws.pdf
deploy:
  provider: pages
  local_dir: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
