# https://github.com/PHPirates/travis-ci-latex-pdf

sudo:       required
language:   generic
services:   docker

# Docs of the options: https://github.com/Strauman/travis-latexbuild/tree/master#configuration-options
tex-config:
- tex-scheme=small
- push-type=none
- build-pattern=main.tex
#- latexmk-flags=-dvi -f
# Check at https://www.ctan.org/pkg/package-name in which TeX Live package a LaTeX package is contained.
- packages=collection-latex, hyperref, etoolbox, fontenc, fontspec, cm-unicode, calc, tocloft

# We will use the docker image from https://hub.docker.com/r/strauman/travis-latexbuild/
script:
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild:small

before_deploy:
  - mkdir pages
  - cp main.pdf pages/LocalConstitutionAndBylaws.pdf
deploy:
  provider: pages
  local_dir: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
